# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creared_date',
            new_name='created_date',
        ),
    ]
